# Generated by Django 5.1.6 on 2025-03-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MaestroApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="testClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("instrument", models.CharField(max_length=200)),
                ("teacher", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("is_group", models.BooleanField(default=False)),
                ("capacity", models.IntegerField(default=20)),
                ("availability", models.BooleanField(default=True)),
            ],
        ),
    ]
