# Generated by Django 5.1.5 on 2025-02-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaestroApp', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaestroAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=1000)),
                ('date_due', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MaestroClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaestroInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('violin', 'Violin'), ('guitar', 'Guitar'), ('piano', 'Piano'), ('drums', 'Drums')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='maestrouser',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='maestrouser',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='maestrouser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='maestrouser',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='MaestroApp.maestrorole'),
        ),
        migrations.AlterField(
            model_name='maestrouser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='maestrouser',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='users', to='MaestroApp.maestroassignment'),
        ),
        migrations.AddField(
            model_name='maestrouser',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='users', to='MaestroApp.maestroclass'),
        ),
        migrations.AddField(
            model_name='maestrouser',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='users', to='MaestroApp.maestroinstrument'),
        ),
        migrations.CreateModel(
            name='MaestroLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.IntegerField(default=60)),
                ('is_group', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('dt', models.DateTimeField()),
                ('associated_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='MaestroApp.maestroclass')),
            ],
        ),
        migrations.AddField(
            model_name='maestroassignment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='MaestroApp.maestrolesson'),
        ),
    ]
