# Generated by Django 5.1.5 on 2025-03-13 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaestroApp', '0002_maestroassignment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestroclass',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
