# Generated by Django 5.1.5 on 2025-03-04 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaestroApp', '0002_testclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestroclass',
            name='capacity',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='maestroclass',
            name='instrument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='MaestroApp.maestroinstrument'),
        ),
    ]
