# Generated by Django 5.1.5 on 2025-03-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaestroApp', '0003_maestroclass_capacity_maestroclass_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestroclass',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
