# Generated by Django 5.1.5 on 2025-03-13 13:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaestroApp', '0003_maestroclass_students'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maestrouser',
            options={'verbose_name': 'Maestro User', 'verbose_name_plural': 'Maestro Users'},
        ),
        migrations.CreateModel(
            name='MaestroNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_type', models.CharField(choices=[('class_added', 'Added to Class'), ('class_removed', 'Removed from Class'), ('lesson_added', 'New Lesson Added'), ('assignment_added', 'New Assignment Added')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('users', models.ManyToManyField(related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='maestrouser',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='recipients', to='MaestroApp.maestronotification'),
        ),
    ]
