# Generated by Django 5.1.5 on 2025-03-08 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaestroApp', '0004_maestroclass_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestroclass',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teaching_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
