# Generated by Django 5.1.5 on 2025-03-15 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaestroApp', '0004_alter_maestrouser_options_maestronotification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestronotification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='maestronotification',
            name='users',
        ),
        migrations.RemoveField(
            model_name='maestrouser',
            name='notifications',
        ),
        migrations.CreateModel(
            name='UserNotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaestroApp.maestronotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notification')},
            },
        ),
    ]
