# Generated by Django 5.1.5 on 2025-03-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaestroApp', '0005_maestroclass_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestroclass',
            name='is_group',
            field=models.BooleanField(default=0),
        ),
    ]
