# Generated by Django 5.1.5 on 2025-03-10 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaestroApp', '0006_maestroclass_is_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestrouser',
            name='role',
        ),
        migrations.DeleteModel(
            name='testClass',
        ),
        migrations.DeleteModel(
            name='MaestroRole',
        ),
    ]
