# Generated by Django 5.1.2 on 2025-03-10 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaestroApp', '0006_maestroclass_is_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestroassignment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaestroApp.maestrolesson'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaestroApp.maestrolesson')),
                ('related_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaestroApp.maestroclass')),
            ],
        ),
    ]
